name: Deploy to Azure SQL

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: '9.0.x'

    - name: Find MSBuild
      id: msbuild
      run: |
        $msbuildPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
        echo "MSBUILD_PATH=$msbuildPath" >> $GITHUB_ENV

    - name: Build project
      run: $env:MSBUILD_PATH /p:Configuration=Release

    - name: Deploy to Azure SQL
      uses: Azure/sql-action@v2.3
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        server-name: testdatabase111.database.windows.net
        database-name: testdatabase111
        authentication-type: 'connection-string'
        sql-file: 'path/to/your/sql/script.sql'


