name: Deploy to Azure SQL

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: '9.0.x'

    - name: Find MSBuild
      id: msbuild
      run: |
        $msbuildPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
        echo "MSBUILD_PATH=$msbuildPath" >> $env:GITHUB_ENV

    - name: Build project
      shell: pwsh
      run: |
        & $env:MSBUILD_PATH /p:Configuration=Release

    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Deploy to Azure SQL
      uses: Azure/sql-action@v2.3
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: './Database1/create.sql'
        action: 'publish'
        arguments: '/p:IncludeCompositeObjects=True'